// <auto-generated />
using System;
using GestaoFinanceira.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestaoFinanceira.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("GestaoFinanceira.Models.Conta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double>("Valor")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Contas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataHora = new DateTime(2022, 6, 21, 11, 52, 18, 414, DateTimeKind.Local).AddTicks(7760),
                            Descricao = "Pago",
                            Valor = 100.0
                        },
                        new
                        {
                            Id = 2,
                            DataHora = new DateTime(2022, 6, 21, 11, 52, 18, 414, DateTimeKind.Local).AddTicks(7781),
                            Descricao = "Pago",
                            Valor = 700.0
                        },
                        new
                        {
                            Id = 3,
                            DataHora = new DateTime(2022, 6, 21, 11, 52, 18, 414, DateTimeKind.Local).AddTicks(7783),
                            Descricao = "Pago",
                            Valor = 50.0
                        });
                });

            modelBuilder.Entity("GestaoFinanceira.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataHoraAlteracao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataHoraCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailLogin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioAlteracao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioCriacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
